---
title: "Healthcare Worker Analysis (Polyclinics) - WOMBAT Study (Jun-Sep 2025)"
output: html_document
---

```{r setup, include=FALSE}

# Libraries
library(readr)
library(tidyverse)  
library(lubridate) 
library(knitr) 
library(kableExtra)
library(DT)
library(patchwork)
library(scales)

DOCTOR_NURSE_FORM_BRB_v1 <- read_csv("data/DOCTOR-NURSE_FORM_BRB_v1_from_03_06_2025_to_09_09_2025.csv", 
                                     col_types = cols(`session date` = col_character(), 
                                                      `session start` = col_time(format = "%H:%M:%S"), 
                                                      `session end` = col_time(format = "%H:%M:%S"), 
                                                      `start time` = col_time(format = "%H:%M:%S"), 
                                                      `end time` = col_time(format = "%H:%M:%S"), 
                                                      `elapsed time` = col_time(format = "%H:%M:%S"), 
                                                      `total time` = col_time(format = "%H:%M:%S"), 
                                                      `active 1` = col_time(format = "%H:%M:%S"))) 
  
DOCTOR_NURSE_FORM_BRB_v2 <- read_csv("data/DOCTOR-NURSE_FORM_BRB_v2_from_03_06_2025_to_09_09_2025.csv", 
                                     col_types = cols(`session date` = col_character(), 
                                                      `session start` = col_time(format = "%H:%M:%S"), 
                                                      `session end` = col_time(format = "%H:%M:%S"), 
                                                      `start time` = col_time(format = "%H:%M:%S"), 
                                                      `end time` = col_time(format = "%H:%M:%S"), 
                                                      `elapsed time` = col_time(format = "%H:%M:%S"), 
                                                      `total time` = col_time(format = "%H:%M:%S"), 
                                                      `active 1` = col_time(format = "%H:%M:%S"))) %>% 
  select(- `[With Whom] Student`) %>%
  rename(`What (DR-NURSE)` = `What (DR-NURSE v2)`,
         `What (DR-NURSE) (subcategories)` = `What (DR-NURSE v2) (subcategories)`,
         `[With Whom] Clerks` = `[With Whom] Clerk`)


wombat_type_professional <- read_delim("data/wombat_type_professional_2.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

data_wmbt_time <- DOCTOR_NURSE_FORM_BRB_v1 %>%
  rbind(DOCTOR_NURSE_FORM_BRB_v2) %>% 
  mutate(total_session = as.numeric(`session end` - `session start`) / 60,
         total_activity = as.numeric(`active 1`) / 60,
         time_slot = case_when(hour(`session start`) %in% 7:11 ~ "morning",
                               hour(`session start`) %in% 12:16 ~ "afternoon",
                               hour(`session start`) %in% 17:20 ~ "evening",
                               TRUE ~ "other"),
         `What (DR-NURSE)` = case_when(`What (DR-NURSE)` == "Inter-Professional Communication" ~ "Professional Communication",
                                       TRUE ~ `What (DR-NURSE)`),
         `What (DR-NURSE) (subcategories)` = case_when(`What (DR-NURSE) (subcategories)` == "Request Tests(Lab, Img, etc)" ~ "Request Tests (Lab, Img, etc)",
                                       TRUE ~ `What (DR-NURSE) (subcategories)`),
         `What (DR-NURSE) (subcategories)` = case_when(`What (DR-NURSE) (subcategories)` == "Other Indiret Care" ~ "Other Indirect Care",
                                                       TRUE ~ `What (DR-NURSE) (subcategories)`),
         task_order = as.numeric(str_extract(`observer/session/task id`, "(?<=_)\\d+$"))) %>% 
   left_join(wombat_type_professional, by = "session id")%>% 
  mutate(`participant id` = coalesce(participant_id_2, `participant id.x`)) %>% 
  filter(!`session id` == 10398,
         !`session id` == 10360)
  
data_wmbt_time_2 <-  data_wmbt_time %>% 
  rename(What = `What (DR-NURSE)`,
         Subcategories = `What (DR-NURSE) (subcategories)`) %>% 
  mutate(with_whom = paste0(
      ifelse(`[With Whom] Doctor` == 1, "Doctor, ", ""),
      ifelse(`[With Whom] Nurse` == 1, "Nurse, ", ""),
      ifelse(`[With Whom] Clerks` == 1, "Clerks, ", ""),
      ifelse(`[With Whom] Patient Relation Reps` == 1, "Patient Relation Reps, ", ""),
      ifelse(`[With Whom] Patient` == 1, "Patient, ", ""),
      ifelse(`[With Whom] Relative` == 1, "Relative, ", ""),
      ifelse(`[With Whom] Allied Health Professional` == 1, "Allied Health Professional, ", ""),
      ifelse(`[With Whom] Other` == 1, "Other, ", "")
    ) %>%
      str_remove_all(", $") %>%
      ifelse(. == "", "No one", .), # los vacios deberian ser NULL no  no one
    how = paste0(
      ifelse(`[How] Paper Based Record` == 1, "Paper, ", ""),
      ifelse(`[How] Desktop Computer` == 1, "Desktop Computer, ", ""),
      ifelse(`[How] Mobile Computer` == 1, "Mobile Computer, ", ""),
      ifelse(`[How] Phone` == 1, "Phone, ", "")
  ) %>%
    str_remove_all(", $") %>%
    ifelse(. == "", "None", .))

```

# Análisis por grupo {.tabset}

## General

### Data Overview

```{r analysis, echo=FALSE}

tipos_profesional <- data_wmbt_time %>% 
  rename(Metric = health_professional_desc) %>% 
  distinct(`participant id`, `session id`, Metric) %>% count(Metric, name = "Count") %>%
  mutate(Metric = case_when(Metric == "Nurse" ~ "- Nurses",
                            Metric == "Doctor" ~ "- Physicians",
                            Metric == "Other" ~ "- Others",
                              TRUE ~ paste0("- ", Metric))) %>% 
  arrange(desc(Count))

general_summary <- tibble(
  Metric = c(
    "Unique sessions", "Unique observers", "Unique HCWs"
  ),
  Count = c(n_distinct(data_wmbt_time$`session id`),
    n_distinct(data_wmbt_time$`observer id`),
    n_distinct(data_wmbt_time$`participant id`)
  )
) %>% 
  rbind(tipos_profesional)

kable(general_summary, caption = "General Data Overview") %>%
  kable_styling(full_width = FALSE)

```

### Observer Statistics

``` {r , echo=FALSE}

observer_summary <- data_wmbt_time %>%
  group_by(`observer id`) %>%
  summarise(
    sessions = n_distinct(`session id`),
    n_activities_avg = mean(table(`session id`), na.rm = TRUE) %>% round(),
    avg_time_min = round(mean(total_session, na.rm = TRUE), 2)
  )

kable(observer_summary, caption = "Session Statistics by Observer") %>%
  kable_styling(full_width = FALSE)

```
<p> Only observer 101172 made 3 comments.</p>

### Activity Analysis

``` {r , echo=FALSE, warning = FALSE}
activity_summary <- data_wmbt_time %>%
  rename(What = `What (DR-NURSE)`) %>% 
  group_by(What) %>%
  summarise(
    total_sessions = n_distinct(`session id`),
    avg_act_session = round(n()/total_sessions),
    total_time_min = sum(total_activity),
    avg_time_min = mean(total_activity),
    max_time_min = max(total_activity),
    min_time_min = min(total_activity)
  ) %>%
  arrange(desc(total_time_min)) %>%
  mutate(across(ends_with("_min"), ~ round(., 2))) %>% 
  mutate(
    pct_time = round((total_time_min / sum(total_time_min)) * 100,1)
  )

kable(activity_summary, caption = "Time Spent per Activity") %>%
  kable_styling(full_width = FALSE)

#Activity 
activity_total_pct <- data_wmbt_time_2 %>%
  group_by(What) %>%
  summarise(
    activity_time = sum(total_activity, na.rm = TRUE),
    .groups = 'drop'
  ) %>% 
  mutate(
    pct_time = round((activity_time / sum(activity_time)) * 100, 1)) 


ggplot(activity_total_pct, aes(x = "", y = pct_time, fill = reorder(What, -pct_time))) +
  geom_col(width = 1, color = "white") +
  coord_polar("y", start = 0) +
  geom_text(
    aes(label = ifelse(pct_time > 2.7, paste0(pct_time, "%"), "")), 
    position = position_stack(vjust = 0.55),
    color = "black",
    size = 3.45) +
  labs(title = paste0("Activity time percentage (%) - Total: ", round(sum(activity_total_pct$activity_time),1)," min"),
    fill = "Category") +
  theme_void() +
  theme(legend.position = "right",
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.text = element_text(size = 10))

sc_activity_time <- data_wmbt_time_2 %>% 
  filter(Subcategories != 0) %>% 
  group_by(What, Subcategories) %>%
  summarise(
    activity_time = sum(total_activity, na.rm = TRUE),
    .groups = 'drop_last' 
  ) %>% 
  group_by(What) %>% 
  mutate(
    pct_time = round((activity_time / sum(activity_time, na.rm = TRUE)) * 100)
  ) %>% 
  ungroup()

g1 <- ggplot(filter(sc_activity_time, What == "Direct Care"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(
    aes(label = paste0(pct_time, "%")), 
    position = position_stack(vjust = 0.55),
    color = "black",
    size = 3.45) +
  labs(title = paste0("Direct Care (", round(sum(activity_summary$total_time_min[activity_summary $What == "Direct Care"]),1)," min)")) +
  theme_void() 

g2 <- ggplot(filter(sc_activity_time, What == "Documentation"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = ifelse(pct_time > 2.5, paste0(pct_time, "%"), "")),
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Documentation (", round(sum(activity_summary$total_time_min[activity_summary$What == "Documentation"]),1)," min)")) +
  theme_void()

g1 + g2

g3 <- ggplot(filter(sc_activity_time, What == "Indirect Care"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = ifelse(pct_time > 2.5, paste0(pct_time, "%"), "")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Indirect Care (", round(sum(activity_summary$total_time_min[activity_summary$What == "Indirect Care"]),1)," min)")) +
  theme_void() +
  theme(
    legend.position = c(1.48, -0.16),  
    plot.margin = margin(20, 100, 20, 20))

g4 <- ggplot(filter(sc_activity_time, What == "Medication Tasks"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Medication Tasks (", round(sum(activity_summary$total_time_min[activity_summary $What == "Medication Tasks"]),1)," min)")) +
  theme_void()

g5 <- ggplot(filter(sc_activity_time, What == "No observation"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = ifelse(pct_time > 2.5, paste0(pct_time, "%"), "")),
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("No observation (", round(sum(activity_summary$total_time_min[activity_summary $What == "No observation"]),1)," min)")) +
  theme_void() 

g6 <- ggplot(filter(sc_activity_time, What == "Other"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Other (", round(sum(activity_summary$total_time_min[activity_summary$What == "Other"]),1)," min)")) +
  theme_void()

g3 + g4
g5 + g6

```

### Tool Usage (How)

``` {r , echo=FALSE}
tool_time_summary <- data_wmbt_time_2 %>%
  filter(!how == "None") %>% 
  group_by(What) %>%
  summarise(
    paper_time = round(sum(total_activity * `[How] Paper Based Record`, na.rm = TRUE), 1),
    computer_time = round(sum(total_activity * `[How] Desktop Computer`, na.rm = TRUE), 1),
    mobile_time = round(sum(total_activity * `[How] Mobile Computer`, na.rm = TRUE), 1),
    phone_time = round(sum(total_activity * `[How] Phone`, na.rm = TRUE), 1),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    .groups = 'drop'
  ) 

tool_table <- tool_time_summary %>%
  select(
    Activity = What,
    `Total Time` = total_time,
    paper_time, computer_time, mobile_time, phone_time
  ) %>%
  arrange(desc(`Total Time`))

kable(tool_table, caption = "Tool Usage by Activity (min)") %>%
  kable_styling(full_width = FALSE)

tool_hm <- tool_time_summary %>%
  select(
    Activity = What,
    `Paper Time` = paper_time,
    `Computer Time` = computer_time,
    `Mobile Time` = mobile_time,
    `Phone Time` = phone_time) 

# Heatmap visualization
tool_hm %>%
  pivot_longer(-Activity, names_to = "Tool", values_to = "Minutes") %>%
ggplot(aes(x = Tool, y = Activity, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white" ,"#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  # Revertir log para leyenda
    breaks = log10(c(1, 10, 100, 1000, 2000))  # Puntos clave
  ) +
  labs(fill = "Minutes") +
  labs(title = "Tool Usage by Activity (min)") +
  theme_minimal()


```

### Location Analysis

``` {r , echo=FALSE}
location_summary <- data_wmbt_time_2 %>%
  group_by(`Where`) %>%
  summarise(
    n_sessions = n_distinct(`session id`),
    total_time_min = sum(total_activity) %>% round(2),
    activities_list = paste(unique(What), collapse = ", ")) %>% 
  arrange(desc(total_time_min))

kable(location_summary, caption = "Observations by Location", booktabs = TRUE) %>%
  kable_styling(full_width = FALSE)

loc_time_summary <- data_wmbt_time_2 %>%
  group_by(What) %>%
  summarise(
    n_act = n(),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    Corridors = round(sum(total_activity[Where == "Corridors"], na.rm = TRUE), 1),
    WorkStation = round(sum(total_activity[Where == "Doctor/Nurse WorkStation"], na.rm = TRUE), 1),
    Observation_Room = round(sum(total_activity[Where == "Observation Room"], na.rm = TRUE), 1),
    Triage_Area = round(sum(total_activity[Where == "Screening/Triage Area"], na.rm = TRUE), 1),
    Treatment_Room = round(sum(total_activity[Where == "Treatment Room"], na.rm = TRUE), 1),
    Other = round(sum(total_activity[Where == "Other"], na.rm = TRUE), 1),
    Ambulance_Bay = round(sum(total_activity[Where == "Ambulance Bay"], na.rm = TRUE), 1),
    Waiting_Area = round(sum(total_activity[Where == "Waiting Area"], na.rm = TRUE), 1),
    XRay_CT = round(sum(total_activity[Where == "X Ray/CT San Unit"], na.rm = TRUE), 1),
    Registration = round(sum(total_activity[Where == "Registration"], na.rm = TRUE), 1),
    Plaster_Room = round(sum(total_activity[Where == "Plaster Room"], na.rm = TRUE), 1),
    Medication_Room = round(sum(total_activity[Where == "Medication Room"], na.rm = TRUE), 1),
    Consultation_Room = round(sum(total_activity[Where == "Consultation Room"], na.rm = TRUE), 1),
    .groups = 'drop'
  ) # %>%
  # mutate(
  #   across(ends_with("_time"), ~ round(., 2)),
  #   pct_corridors = round((Corridors / total_time) * 100, 1),
  #   pct_workstation = round((WorkStation / total_time) * 100, 1),
  #   pct_observation_room = round((Observation_Room / total_time) * 100, 1),
  #   pct_triage_Area = round((Triage_Area / total_time) * 100, 1),
  #   pct_treatment_Room = round((Treatment_Room / total_time) * 100, 1),
  #   pct_other = round((Other / total_time) * 100, 1),
  #   pct_ambulance_Bay = round((Ambulance_Bay / total_time) * 100, 1),
  #   pct_waiting_Area = round((Waiting_Area / total_time) * 100, 1),
  #   pct_xray_CT = round((XRay_CT / total_time) * 100, 1),
  #   pct_registration = round((Registration / total_time) * 100, 1),
  #   pct_plaster_Room = round((Plaster_Room / total_time) * 100, 1),
  #   pct_medication_Room = round((Medication_Room / total_time) * 100, 1), 
  #   pct_consultation_Room = round((Consultation_Room / total_time) * 100, 1)) 

loc_table <- loc_time_summary %>%
  select(What, total_time,n_act,
    Corridors, WorkStation, Observation_Room, Triage_Area, Treatment_Room, Other, Ambulance_Bay, Waiting_Area, -XRay_CT, Registration, -Plaster_Room, -Medication_Room, Consultation_Room) %>%
  arrange(desc(total_time))

kable(loc_table, caption = "Location by Activity (Min)") %>%
  kable_styling(full_width = FALSE)

loc_hm <- loc_time_summary %>%
  select(What, Corridors,WorkStation, Observation_Room, Triage_Area, Treatment_Room,
         Other, Ambulance_Bay, Waiting_Area, -XRay_CT, Registration, -Plaster_Room, -Medication_Room, Consultation_Room) 

# Heatmap visualization
loc_hm %>%
  pivot_longer(-What, names_to = "Location", values_to = "Minutes") %>%
ggplot(aes(x = Location, y = What, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white" ,"#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  
    breaks = log10(c(1, 10, 100, 1000, 2000))) +
  labs(fill = "Minutes") +
  labs(title = "Location by Activity (min)") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9))

```
### Tool Usage by Location

``` {r , echo=FALSE}
tool_loc_summary <- data_wmbt_time_2 %>%
  filter(!how == "None") %>% 
  group_by(Where) %>%
  summarise(
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    paper_time = round(sum(total_activity * `[How] Paper Based Record`, na.rm = TRUE), 1),
    computer_time = round(sum(total_activity * `[How] Desktop Computer`, na.rm = TRUE), 1),
    mobile_time = round(sum(total_activity * `[How] Mobile Computer`, na.rm = TRUE), 1),
    phone_time = round(sum(total_activity * `[How] Phone`, na.rm = TRUE), 1),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    .groups = 'drop'
  ) 


kable(tool_loc_summary, caption = "Tool Usage by Location (min)") %>%
  kable_styling(full_width = FALSE)

tool_loc <- tool_loc_summary %>%
  select(
    Location = Where,
    `Paper Time` = paper_time,
    `Computer Time` = computer_time,
    `Mobile Time` = mobile_time,
    `Phone Time` = phone_time) 

# Heatmap visualization
tool_loc %>%
  pivot_longer(-Location, names_to = "Tool", values_to = "Minutes") %>%
ggplot(aes(x = Tool, y = Location, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white","#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  # Revertir log para leyenda
    breaks = log10(c(1, 10, 100, 1000, 2000))  # Puntos clave
  ) +
  labs(fill = "Minutes") +
  labs(title = "Tool Usage by Location (min)") +
  theme_minimal()

```

## Nurses

``` {r , echo=FALSE, warning = FALSE}
activity_summary_nurse <- data_wmbt_time %>%
  filter(health_professional_desc == "Nurse") %>% 
  rename(What = `What (DR-NURSE)`) %>% 
  group_by(What) %>%
  summarise(
    total_sessions = n_distinct(`session id`),
    avg_act_session = round(n()/total_sessions),
    total_time_min = sum(total_activity),
    avg_time_min = mean(total_activity),
    max_time_min = max(total_activity),
    min_time_min = min(total_activity)
  ) %>%
  arrange(desc(total_time_min)) %>%
  mutate(across(ends_with("_min"), ~ round(., 2))) %>% 
  mutate(
    pct_time = round((total_time_min / sum(total_time_min)) * 100,1)
  )

kable(activity_summary_nurse, caption = "Time Spent per Activity (Nurses)") %>%
  kable_styling(full_width = FALSE)


```

``` {r , echo=FALSE, warning = FALSE}
#Activity 
activity_total_pct_nurse <- data_wmbt_time_2 %>%
  filter(health_professional_desc == "Nurse") %>% 
  group_by(health_professional_desc, What) %>%
  summarise(
    activity_time = sum(total_activity, na.rm = TRUE),
    .groups = 'drop'
  ) %>% 
  mutate(
    pct_time = round((activity_time / sum(activity_time)) * 100, 1)) 


ggplot(activity_total_pct_nurse, aes(x = "", y = pct_time, fill = reorder(What, -pct_time))) +
  geom_col(width = 1, color = "white") +
  coord_polar("y", start = 0) +
  geom_text(
    aes(label = ifelse(pct_time > 3.5, paste0(pct_time, "%"), "")),
    position = position_stack(vjust = 0.55),
    color = "black",
    size = 3.45) +
  labs(title = paste0("Activity time percentage (%) - Nurse - Total: ", round(sum(activity_total_pct_nurse$activity_time),1)," min"),
    fill = "Category") +
  theme_void() +
  theme(legend.position = "right",
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.text = element_text(size = 10))

sc_activity_time_nurse <- data_wmbt_time_2 %>% 
  filter(health_professional_desc == "Nurse") %>% 
  filter(Subcategories != 0) %>% 
  group_by(What, Subcategories) %>%
  summarise(
    activity_time = sum(total_activity, na.rm = TRUE),
    .groups = 'drop_last' 
  ) %>% 
  group_by(What) %>% 
  mutate(
    pct_time = round((activity_time / sum(activity_time, na.rm = TRUE)) * 100, 1)
  ) %>% 
  ungroup()

n1 <- ggplot(filter(sc_activity_time_nurse, What == "Direct Care"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")), 
            position = position_stack(vjust = 0.52), size = 3) +
  labs(title = paste0("Direct Care (", round(sum(sc_activity_time_nurse$activity_time[sc_activity_time_nurse$What == "Direct Care"]),1)," min)")) +
  theme_void() 

n2 <- ggplot(filter(sc_activity_time_nurse, What == "Other"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Other (", round(sum(sc_activity_time_nurse$activity_time[sc_activity_time_nurse$What == "Other"]),1)," min)")) +
  theme_void()

n1 + n2

n3 <- ggplot(filter(sc_activity_time_nurse, What == "No observation"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = ifelse(pct_time > 2, paste0(pct_time, "%"), "")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("No observation (", round(sum(sc_activity_time_nurse$activity_time[sc_activity_time_nurse$What == "No observation"]),1)," min)")) +
  theme_void() 

n4 <- ggplot(filter(sc_activity_time_nurse, What == "Indirect Care"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = ifelse(pct_time > 5, paste0(pct_time, "%"), "")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Indirect Care (", round(sum(sc_activity_time_nurse$activity_time[sc_activity_time_nurse$What == "Indirect Care"]),1)," min)")) +
  theme_void() +
  theme(
    legend.position = c(1.48, -0.16),  
    plot.margin = margin(20, 100, 20, 20))


n5 <- ggplot(filter(sc_activity_time_nurse, What == "Documentation"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = ifelse(pct_time > 14, paste0(pct_time, "%"), "")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Documentation (", round(sum(sc_activity_time_nurse$activity_time[sc_activity_time_nurse $What == "Documentation"]),1)," min)")) +
  theme_void()

n6 <- ggplot(filter(sc_activity_time_nurse, What == "Medication Tasks"),
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")),
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Medication Tasks (", round(sum(sc_activity_time_nurse$activity_time[sc_activity_time_nurse$What == "Medication Tasks"]),1)," min)")) +
  theme_void()


n3 + n4
n5 + n6


```
### Tool Usage (How)

``` {r , echo=FALSE}

tool_time_summary_nurse <- data_wmbt_time_2 %>%
  filter(!how == "None", 
         health_professional_desc == "Nurse") %>% 
  group_by(What) %>%
  summarise(
    paper_time = round(sum(total_activity * `[How] Paper Based Record`, na.rm = TRUE), 1),
    computer_time = round(sum(total_activity * `[How] Desktop Computer`, na.rm = TRUE), 1),
    mobile_time = round(sum(total_activity * `[How] Mobile Computer`, na.rm = TRUE), 1),
    phone_time = round(sum(total_activity * `[How] Phone`, na.rm = TRUE), 1),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    .groups = 'drop'
  ) 

tool_table_nurse <- tool_time_summary_nurse %>%
  select(
    Activity = What,
    `Total Time` = total_time,
    paper_time, computer_time, mobile_time, phone_time
  ) %>%
  arrange(desc(`Total Time`))

kable(tool_table_nurse, caption = "Tool Usage by Activity - Nurses (min)") %>%
  kable_styling(full_width = FALSE)

tool_hm_nurse <- tool_time_summary_nurse %>%
  select(
    Activity = What,
    `Paper Time` = paper_time,
    `Computer Time` = computer_time,
    `Mobile Time` = mobile_time,
    `Phone Time` = phone_time) 

# Heatmap
tool_hm_nurse %>%
  pivot_longer(-Activity, names_to = "Tool", values_to = "Minutes") %>%
ggplot(aes(x = Tool, y = Activity, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white" ,"#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  # Revertir log para leyenda
    breaks = log10(c(1, 10, 100, 1000, 2000))  
  ) +
  labs(fill = "Minutes") +
  labs(title = "Tool Usage by Activity - Nurses (min)") +
  theme_minimal()

```
### Location Analysis - Nurses

``` {r , echo=FALSE}
location_summary_nurse <- data_wmbt_time_2 %>%
  filter(health_professional_desc == "Nurse") %>% 
  group_by(`Where`) %>%
  summarise(
    n_sessions = n_distinct(`session id`),
    total_time_min = sum(total_activity) %>% round(2),
    activities_list = paste(unique(What), collapse = ", ")) %>% 
  arrange(desc(total_time_min))

kable(location_summary_nurse, caption = "Observations by Location", booktabs = TRUE) %>%
  kable_styling(full_width = FALSE)

loc_time_summary_nurse <- data_wmbt_time_2 %>%
  filter(health_professional_desc == "Nurse") %>% 
  group_by(What) %>%
  summarise(
    n_act = n(),
    total_time = round(sum(total_activity, na.rm = TRUE),1),
    Corridors = round(sum(total_activity[Where == "Corridors"], na.rm = TRUE), 1),
    WorkStation = round(sum(total_activity[Where == "Doctor/Nurse WorkStation"], na.rm = TRUE), 1),
    Observation_Room = round(sum(total_activity[Where == "Observation Room"], na.rm = TRUE), 1),
    Triage_Area = round(sum(total_activity[Where == "Screening/Triage Area"], na.rm = TRUE), 1),
    Treatment_Room = round(sum(total_activity[Where == "Treatment Room"], na.rm = TRUE), 1),
    Other = round(sum(total_activity[Where == "Other"], na.rm = TRUE), 1),
    Ambulance_Bay = round(sum(total_activity[Where == "Ambulance Bay"], na.rm = TRUE), 1),
    Waiting_Area = round(sum(total_activity[Where == "Waiting Area"], na.rm = TRUE), 1),
    XRay_CT = round(sum(total_activity[Where == "X Ray/CT San Unit"], na.rm = TRUE), 1),
    Registration = round(sum(total_activity[Where == "Registration"], na.rm = TRUE), 1),
    Plaster_Room = round(sum(total_activity[Where == "Plaster Room"], na.rm = TRUE), 1),
    Medication_Room = round(sum(total_activity[Where == "Medication Room"], na.rm = TRUE), 1),
    Consultation_Room = round(sum(total_activity[Where == "Consultation Room"], na.rm = TRUE), 1),
    .groups = 'drop'
  ) # %>%
  # mutate(
  #   across(ends_with("_time"), ~ round(., 2)),
  #   pct_corridors = round((Corridors / total_time) * 100, 1),
  #   pct_workstation = round((WorkStation / total_time) * 100, 1),
  #   pct_observation_room = round((Observation_Room / total_time) * 100, 1),
  #   pct_triage_Area = round((Triage_Area / total_time) * 100, 1),
  #   pct_treatment_Room = round((Treatment_Room / total_time) * 100, 1),
  #   pct_other = round((Other / total_time) * 100, 1),
  #   pct_ambulance_Bay = round((Ambulance_Bay / total_time) * 100, 1),
  #   pct_waiting_Area = round((Waiting_Area / total_time) * 100, 1),
  #   pct_xray_CT = round((XRay_CT / total_time) * 100, 1),
  #   pct_registration = round((Registration / total_time) * 100, 1),
  #   pct_plaster_Room = round((Plaster_Room / total_time) * 100, 1),
  #   pct_medication_Room = round((Medication_Room / total_time) * 100, 1), 
  #   pct_consultation_Room = round((Consultation_Room / total_time) * 100, 1)) 

loc_table_nurse <- loc_time_summary_nurse %>%
  select(What, total_time,n_act,
    Corridors, WorkStation, Observation_Room, Triage_Area, Treatment_Room, Other, Ambulance_Bay, Waiting_Area, -XRay_CT, Registration, -Plaster_Room, -Medication_Room, Consultation_Room) %>%
  arrange(desc(total_time))

kable(loc_table_nurse, caption = "Location by Activity (%)") %>%
  kable_styling(full_width = FALSE)

loc_hm_nurse <- loc_time_summary_nurse %>%
  select(What, Corridors,WorkStation, Observation_Room, Triage_Area, Treatment_Room,
         Other, Ambulance_Bay, Waiting_Area, -XRay_CT, Registration, -Plaster_Room,
         -Medication_Room, Consultation_Room) 

# Heatmap visualization
loc_hm_nurse %>%
  pivot_longer(-What, names_to = "Location", values_to = "Minutes") %>%
ggplot(aes(x = Location, y = What, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white","#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  
    breaks = log10(c(1, 10, 100, 1000, 2000))) +
  labs(fill = "Minutes") +
  labs(title = "Location by Activity (min)") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9))

```

### Tool Usage by Location (Nurses)

``` {r , echo=FALSE}
tool_loc_summary <- data_wmbt_time_2 %>%
  filter(!how == "None") %>% 
  filter(health_professional_desc == "Nurse") %>% 
  group_by(Where) %>%
  summarise(
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    paper_time = round(sum(total_activity * `[How] Paper Based Record`, na.rm = TRUE), 1),
    computer_time = round(sum(total_activity * `[How] Desktop Computer`, na.rm = TRUE), 1),
    mobile_time = round(sum(total_activity * `[How] Mobile Computer`, na.rm = TRUE), 1),
    phone_time = round(sum(total_activity * `[How] Phone`, na.rm = TRUE), 1),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    .groups = 'drop'
  ) 


kable(tool_loc_summary, caption = "Tool Usage by Location (min) - Nurses") %>%
  kable_styling(full_width = FALSE)

tool_loc <- tool_loc_summary %>%
  select(
    Location = Where,
    `Paper Time` = paper_time,
    `Computer Time` = computer_time,
    `Mobile Time` = mobile_time,
    `Phone Time` = phone_time) 

# Heatmap visualization
tool_loc %>%
  pivot_longer(-Location, names_to = "Tool", values_to = "Minutes") %>%
ggplot(aes(x = Tool, y = Location, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white","#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  # Revertir log para leyenda
    breaks = log10(c(1, 10, 100, 1000, 2000))  # Puntos clave
  ) +
  labs(fill = "Minutes") +
  labs(title = "Tool Usage by Location (min) - Nurses") +
  theme_minimal()

```

## Physician

``` {r , echo=FALSE, warning = FALSE}

activity_summary_physician <- data_wmbt_time %>%
  filter(health_professional_desc == "Physician") %>% 
  rename(What = `What (DR-NURSE)`) %>% 
  group_by(What) %>%
  summarise(
    total_sessions = n_distinct(`session id`),
    avg_act_session = round(n()/total_sessions),
    total_time_min = sum(total_activity),
    avg_time_min = mean(total_activity),
    max_time_min = max(total_activity),
    min_time_min = min(total_activity)
  ) %>%
  arrange(desc(total_time_min)) %>%
  mutate(across(ends_with("_min"), ~ round(., 2))) %>% 
  mutate(
    pct_time = round((total_time_min / sum(total_time_min)) * 100, 1)
  )

kable(activity_summary_physician, caption = "Time Spent per Activity (Physician)") %>%
  kable_styling(full_width = FALSE)

activity_total_pct_physician <- data_wmbt_time_2 %>%
  filter(health_professional_desc == "Physician") %>% 
  group_by(health_professional_desc, What) %>%
  summarise(
    activity_time = sum(total_activity, na.rm = TRUE),
    .groups = 'drop'
  ) %>% 
  mutate(
    pct_time = round((activity_time / sum(activity_time)) * 100, 1))

ggplot(activity_total_pct_physician, aes(x = "", y = pct_time, fill = reorder(What, -pct_time))) +
  geom_col(width = 1, color = "white") +
  coord_polar("y", start = 0) +
  geom_text(aes(label = ifelse(pct_time > 3, paste0(pct_time, "%"), "")),
    position = position_stack(vjust = 0.55),
    color = "black",
    size = 3.5) +
  labs(title = paste0("Activity time percentage (%) - Phisycian - Total: ", round(sum(activity_total_pct_nurse$activity_time),1)," min"),
    fill = "Category") +
  theme_void() +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.text = element_text(size = 10))

## Subcategories
sc_activity_time_physician <- data_wmbt_time_2 %>% 
  filter(health_professional_desc == "Physician") %>% 
  filter(Subcategories != 0) %>% 
  group_by(What, Subcategories) %>%
  summarise(
    activity_time = sum(total_activity, na.rm = TRUE),
    .groups = 'drop_last' 
  ) %>% 
  group_by(What) %>% 
  mutate(
    pct_time = round((activity_time / sum(activity_time, na.rm = TRUE)) * 100, 1)
  ) %>% 
  ungroup()

p1 <- ggplot(filter(sc_activity_time_physician, What == "Direct Care"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Direct Care (", round(sum(sc_activity_time_physician$activity_time[sc_activity_time_physician $What == "Direct Care"]),1)," min)")) +
  theme_void() 

p2 <- ggplot(filter(sc_activity_time_physician, What == "Documentation"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = ifelse(pct_time > 7, paste0(pct_time, "%"), "")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Documentation (", round(sum(sc_activity_time_physician$activity_time[sc_activity_time_physician$What == "Documentation"]),1)," min)")) +
  theme_void()

p1 + p2

p3 <- ggplot(filter(sc_activity_time_physician, What == "Medication Tasks"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  geom_text(aes(label = ifelse(pct_time > 7, paste0(pct_time, "%"), "")), 
            position = position_stack(vjust = 0.55), size = 3) +
  coord_polar("y") +
  labs(title = paste0("Medication Tasks (", round(sum(sc_activity_time_physician$activity_time[sc_activity_time_physician$What == "Medication Tasks"]),1)," min)")) +
  theme_void()

p4 <- ggplot(filter(sc_activity_time_physician, What == "Indirect Care"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = ifelse(pct_time > 7, paste0(pct_time, "%"), "")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Indirect Care (", round(sum(sc_activity_time_physician$activity_time[sc_activity_time_physician$What == "Indirect Care"]),1)," min)")) +
  theme_void()  +
  theme(
    legend.position = c(1.48, -0.16),  
    plot.margin = margin(20, 100, 20, 20))

p5 <- ggplot(filter(sc_activity_time_physician, What == "No observation"),
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")),
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("No observation (", round(sum(sc_activity_time_physician$activity_time[sc_activity_time_physician$What == "No observation"]),1)," min)")) +
  theme_void()

p6 <- ggplot(filter(sc_activity_time_physician, What == "Other"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("Other (", round(sum(sc_activity_time_physician$activity_time[sc_activity_time_physician$What == "Other"]),1)," min)")) +
  theme_void()

p3 + p4

p5 + p6

```
### Tool Usage Physician (How)

``` {r , echo=FALSE}

tool_time_summary_physician <- data_wmbt_time_2 %>%
  filter(!how == "None", 
         health_professional_desc == "Physician") %>% 
  group_by(What) %>%
  summarise(
    paper_time = round(sum(total_activity * `[How] Paper Based Record`, na.rm = TRUE), 1),
    computer_time = round(sum(total_activity * `[How] Desktop Computer`, na.rm = TRUE), 1),
    mobile_time = round(sum(total_activity * `[How] Mobile Computer`, na.rm = TRUE), 1),
    phone_time = round(sum(total_activity * `[How] Phone`, na.rm = TRUE), 1),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    .groups = 'drop'
  ) 

tool_table_physician <- tool_time_summary_physician %>%
  select(
    Activity = What,
    `Total Time` = total_time,
    paper_time, computer_time, mobile_time, phone_time
  ) %>%
  arrange(desc(`Total Time`))

kable(tool_table_physician, caption = "Tool Usage by Activity - Physicians (min)") %>%
  kable_styling(full_width = FALSE)

tool_hm_physician <- tool_time_summary_physician %>%
  select(
    Activity = What,
    `Paper Time` = paper_time,
    `Computer Time` = computer_time,
    `Mobile Time` = mobile_time,
    `Phone Time` = phone_time) 

# Heatmap
tool_hm_physician %>%
  pivot_longer(-Activity, names_to = "Tool", values_to = "Minutes") %>%
ggplot(aes(x = Tool, y = Activity, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white" ,"#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  # Revertir log para leyenda
    breaks = log10(c(1, 10, 100, 1000, 2000))  
  ) +
  labs(fill = "Minutes") +
  labs(title = "Tool Usage by Activity - Physician (min)") +
  theme_minimal()
```

### Location Analysis - Physician

``` {r , echo=FALSE}
location_summary_physician <- data_wmbt_time_2 %>%
  filter(health_professional_desc == "Physician") %>% 
  group_by(`Where`) %>%
  summarise(
    n_sessions = n_distinct(`session id`),
    total_time_min = sum(total_activity) %>% round(2),
    activities_list = paste(unique(What), collapse = ", ")) %>% 
  arrange(desc(total_time_min))

kable(location_summary_physician, caption = "Observations by Location", booktabs = TRUE) %>%
  kable_styling(full_width = FALSE)

loc_time_summary_physician <- data_wmbt_time_2 %>%
  filter(health_professional_desc == "Physician") %>% 
  group_by(What) %>%
  summarise(
    n_act = n(),
    total_time = round(sum(total_activity, na.rm = TRUE),1),
    Corridors = round(sum(total_activity[Where == "Corridors"], na.rm = TRUE), 1),
    WorkStation = round(sum(total_activity[Where == "Doctor/Nurse WorkStation"], na.rm = TRUE), 1),
    Observation_Room = round(sum(total_activity[Where == "Observation Room"], na.rm = TRUE), 1),
    Triage_Area = round(sum(total_activity[Where == "Screening/Triage Area"], na.rm = TRUE), 1),
    Treatment_Room = round(sum(total_activity[Where == "Treatment Room"], na.rm = TRUE), 1),
    Other = round(sum(total_activity[Where == "Other"], na.rm = TRUE), 1),
    Ambulance_Bay = round(sum(total_activity[Where == "Ambulance Bay"], na.rm = TRUE), 1),
    Waiting_Area = round(sum(total_activity[Where == "Waiting Area"], na.rm = TRUE), 1),
    XRay_CT = round(sum(total_activity[Where == "X Ray/CT San Unit"], na.rm = TRUE), 1),
    Registration = round(sum(total_activity[Where == "Registration"], na.rm = TRUE), 1),
    Plaster_Room = round(sum(total_activity[Where == "Plaster Room"], na.rm = TRUE), 1),
    Medication_Room = round(sum(total_activity[Where == "Medication Room"], na.rm = TRUE), 1),
    Consultation_Room = round(sum(total_activity[Where == "Consultation Room"], na.rm = TRUE), 1),
    .groups = 'drop'
  ) 

loc_table_physician <- loc_time_summary_physician %>%
  select(What, total_time,n_act,
    Corridors, WorkStation, Observation_Room, Triage_Area, Treatment_Room, Other, -Ambulance_Bay, Waiting_Area, -XRay_CT, Registration, -Plaster_Room, -Medication_Room, Consultation_Room) %>%
  arrange(desc(total_time))

kable(loc_table_physician, caption = "Location by Activity (%)") %>%
  kable_styling(full_width = FALSE)

loc_hm_physician <- loc_time_summary_physician %>%
  select(What, Corridors,WorkStation, Observation_Room, Triage_Area, Treatment_Room,
         Other, -Ambulance_Bay, Waiting_Area, -XRay_CT, Registration, -Plaster_Room,
         -Medication_Room, Consultation_Room) 

# Heatmap visualization
loc_hm_physician %>%
  pivot_longer(-What, names_to = "Location", values_to = "Minutes") %>%
ggplot(aes(x = Location, y = What, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white" ,"#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  
    breaks = log10(c(1, 10, 100, 1000, 2000))) +
  labs(fill = "Minutes") +
  labs(title = "Location by Activity (min)") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9))

```
### Tool Usage by Location (Physician)

``` {r , echo=FALSE}
tool_loc_summary <- data_wmbt_time_2 %>%
  filter(!how == "None") %>% 
  filter(health_professional_desc == "Physician") %>% 
  group_by(Where) %>%
  summarise(
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    paper_time = round(sum(total_activity * `[How] Paper Based Record`, na.rm = TRUE), 1),
    computer_time = round(sum(total_activity * `[How] Desktop Computer`, na.rm = TRUE), 1),
    mobile_time = round(sum(total_activity * `[How] Mobile Computer`, na.rm = TRUE), 1),
    phone_time = round(sum(total_activity * `[How] Phone`, na.rm = TRUE), 1),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    .groups = 'drop'
  ) 


kable(tool_loc_summary, caption = "Tool Usage by Location (min) - Physician") %>%
  kable_styling(full_width = FALSE)

tool_loc <- tool_loc_summary %>%
  select(
    Location = Where,
    `Paper Time` = paper_time,
    `Computer Time` = computer_time,
    `Mobile Time` = mobile_time,
    `Phone Time` = phone_time) 

# Heatmap visualization
tool_loc %>%
  pivot_longer(-Location, names_to = "Tool", values_to = "Minutes") %>%
ggplot(aes(x = Tool, y = Location, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white","#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  # Revertir log para leyenda
    breaks = log10(c(1, 10, 100, 1000, 2000))  # Puntos clave
  ) +
  labs(fill = "Minutes") +
  labs(title = "Tool Usage by Location (min) - Physician") +
  theme_minimal()

```
