---
title: "Healthcare Worker Analysis (QEH) - WOMBAT Study (Clerks Mar-Apr 2025)"
output: html_document
---

```{r setup, include=FALSE}

# Libraries
library(readr)
library(tidyverse)  
library(lubridate) 
library(knitr) 
library(kableExtra)
library(DT)
library(patchwork)
library(hms)
library(scales)

q_wombat_type_professional <- read_delim("data/wombat_type_professional.csv", 
                                         delim = ";", escape_double = FALSE, trim_ws = TRUE) %>% 
  select(`session id`, `health_professional_desc`)

p_wombat_type_professional <- read_delim("data/wombat_type_professional_2.csv", 
                                         delim = ";", escape_double = FALSE, trim_ws = TRUE) %>% 
  select(`session id`, `health_professional_desc`)

RECORD_CLERK_FORM_BRB_v1_from_23_03_2025_to_24_04_2025 <- read_csv("data/RECORD_CLERK_FORM_BRB_v1_from_23_03_2025_to_24_04_2025.csv", 
                                                                   col_types = cols(`session start` = col_time(format = "%H:%M:%S"), 
                                                                                    `session end` = col_time(format = "%H:%M:%S"), 
                                                                                    `start time` = col_time(format = "%H:%M:%S"), 
                                                                                    `end time` = col_time(format = "%H:%M:%S"), 
                                                                                    `elapsed time` = col_time(format = "%H:%M:%S"), 
                                                                                    `total time` = col_time(format = "%H:%M:%S"), 
                                                                                    `active 1` = col_time(format = "%H:%M:%S")))

data_wmbt_time <- RECORD_CLERK_FORM_BRB_v1_from_23_03_2025_to_24_04_2025 %>% 
  left_join(q_wombat_type_professional, by = "session id") %>% 
  left_join(p_wombat_type_professional, by = "session id") %>% 
  mutate(health_professional_desc = coalesce(health_professional_desc.x, health_professional_desc.y)) %>% 
  select(-health_professional_desc.x, -health_professional_desc.y) %>% 
  mutate(total_session = as.numeric(`session end` - `session start`) / 60,
    total_activity = as.numeric(`active 1`) / 60,
    time_slot = case_when(hour(`session start`) %in% 7:11 ~ "morning",
                          hour(`session start`) %in% 12:16 ~ "afternoon",
                          hour(`session start`) %in% 17:20 ~ "evening",
                          TRUE ~ "other"),
    task_order = as.numeric(str_extract(`observer/session/task id`, "(?<=_)\\d+$")))


data_wmbt_time_2 <-  data_wmbt_time %>% 
  rename(What = `What (RECORD CLERK)`,
         Subcategories = `What (RECORD CLERK) (subcategories)`) %>% 
  mutate(with_whom = paste0(
    ifelse(`[With Whom] Doctor` == 1, "Doctor, ", ""),
    ifelse(`[With Whom] Nurse` == 1, "Nurse, ", ""),
    ifelse(`[With Whom] Patient` == 1, "Patient, ", ""),
    ifelse(`[With Whom] Relative` == 1, "Relative, ", ""),
    ifelse(`[With Whom] Allied Health Professional` == 1, "Allied Health Professional, ", ""),
    ifelse(`[With Whom] Other` == 1, "Other, ", "")
  ) %>%
    str_remove_all(", $") %>%
    ifelse(. == "", "No one", .), # los vacios deberian ser NULL no  no one
  how = paste0(
    ifelse(`[How] Paper Based Record` == 1, "Paper, ", ""),
    ifelse(`[How] Desktop Computer` == 1, "Desktop Computer, ", ""),
    ifelse(`[How] Mobile Computer` == 1, "Mobile Computer, ", ""),
    ifelse(`[How] Phone` == 1, "Phone, ", "")
  ) %>%
    str_remove_all(", $") %>%
    ifelse(. == "", "None", .)) 
```

### Data Overview

```{r analysis, echo=FALSE}

general_summary <- tibble(
  Metric = c(
    "Unique sessions", "Unique observers", "Unique HCWs"
  ),
  Count = c(n_distinct(data_wmbt_time$`session id`),
    n_distinct(data_wmbt_time$`observer id`),
    n_distinct(data_wmbt_time$`participant id`)
  )
) 

kable(general_summary, caption = "General Data Overview") %>%
  kable_styling(full_width = FALSE)

```

### Observer Statistics

``` {r , echo=FALSE}

observer_summary <- data_wmbt_time %>%
  group_by(`observer id`) %>%
  summarise(
    sessions = n_distinct(`session id`),
    n_activities_avg = mean(table(`session id`), na.rm = TRUE) %>% round(),
    avg_time_min = round(mean(total_session, na.rm = TRUE), 2)
  )

kable(observer_summary, caption = "Session Statistics by Observer") %>%
  kable_styling(full_width = FALSE)

```


### Activity Analysis

``` {r , echo=FALSE, warning = FALSE}
activity_summary <- data_wmbt_time %>%
  rename(What = `What (RECORD CLERK)`) %>% 
  group_by(What) %>%
  summarise(
    total_sessions = n_distinct(`session id`),
    avg_act_session = round(n()/total_sessions),
    total_time_min = sum(total_activity),
    avg_time_min = mean(total_activity),
    max_time_min = max(total_activity),
    min_time_min = min(total_activity)
  ) %>%
  arrange(desc(total_time_min)) %>%
  mutate(across(ends_with("_min"), ~ round(., 2))) %>% 
  mutate(
    pct_time = round((total_time_min / sum(total_time_min)) * 100,1)
  )

kable(activity_summary, caption = "Time Spent per Activity") %>%
  kable_styling(full_width = FALSE)

#check subcategories
# prueba <- data_wmbt_time %>% distinct(`What (DR-NURSE)`, `What (DR-NURSE) (subcategories)`)

#Activity 
activity_total_pct <- data_wmbt_time_2 %>%
  group_by(What) %>%
  summarise(
    activity_time = sum(total_activity, na.rm = TRUE),
    .groups = 'drop'
  ) %>% 
  mutate(
    pct_time = round((activity_time / sum(activity_time)) * 100, 1)) 

ggplot(activity_total_pct, aes(x = "", y = pct_time, fill = reorder(What, -pct_time))) +
  geom_col(width = 1, color = "white") +
  coord_polar("y", start = 0) +
  geom_text(
    aes(label = ifelse(pct_time > 2.7, paste0(pct_time, "%"), "")), 
    position = position_stack(vjust = 0.55),
    color = "black",
    size = 3.45) +
  labs(title = paste0("Activity time percentage (%) - Total: ", round(sum(activity_total_pct$activity_time),1)," min"),
    fill = "Category") +
  theme_void() +
  theme(legend.position = "right",
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.text = element_text(size = 10))

sc_activity_time <- data_wmbt_time_2 %>% 
  filter(Subcategories != 0) %>% 
  group_by(What, Subcategories) %>%
  summarise(
    activity_time = sum(total_activity, na.rm = TRUE),
    .groups = 'drop_last' 
  ) %>% 
  group_by(What) %>% 
  mutate(
    pct_time = round((activity_time / sum(activity_time, na.rm = TRUE)) * 100)
  ) %>% 
  ungroup()

g1 <- ggplot(filter(sc_activity_time, What == "Record Management"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(
    aes(label = paste0(pct_time, "%")), 
    position = position_stack(vjust = 0.55),
    color = "black",
    size = 3.45) +
  labs(title = paste0("Record Management (", round(sum(activity_summary$total_time_min[activity_summary $What == "Record Management"]),1)," min)")) +
  theme_void() 

g2 <- ggplot(filter(sc_activity_time, What == "No Observation"), 
             aes(x = "", y = pct_time, fill = Subcategories)) +
  geom_col(width = 1, color = "white") +
  coord_polar("y") +
  geom_text(aes(label = paste0(pct_time, "%")), 
            position = position_stack(vjust = 0.55), size = 3) +
  labs(title = paste0("No Observation (", round(sum(activity_summary$total_time_min[activity_summary$What == "No Observation"]),1)," min)")) +
  theme_void()

g1 + g2

```

### Tool Usage (How)

``` {r , echo=FALSE}
tool_time_summary <- data_wmbt_time_2 %>%
  filter(!how == "None") %>% 
  group_by(What) %>%
  summarise(
    paper_time = round(sum(total_activity * `[How] Paper Based Record`, na.rm = TRUE), 1),
    computer_time = round(sum(total_activity * `[How] Desktop Computer`, na.rm = TRUE), 1),
    mobile_time = round(sum(total_activity * `[How] Mobile Computer`, na.rm = TRUE), 1),
    phone_time = round(sum(total_activity * `[How] Phone`, na.rm = TRUE), 1),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    .groups = 'drop'
  ) 

tool_table <- tool_time_summary %>%
  select(
    Activity = What,
    `Total Time` = total_time,
    paper_time, computer_time, mobile_time, phone_time
  ) %>%
  arrange(desc(`Total Time`))

kable(tool_table, caption = "Tool Usage by Activity (min)") %>%
  kable_styling(full_width = FALSE)

tool_hm <- tool_time_summary %>%
  select(
    Activity = What,
    `Paper Time` = paper_time,
    `Computer Time` = computer_time,
    `Mobile Time` = mobile_time,
    `Phone Time` = phone_time) 

# Heatmap visualization
tool_hm %>%
  pivot_longer(-Activity, names_to = "Tool", values_to = "Minutes") %>%
ggplot(aes(x = Tool, y = Activity, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white","#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  # Revertir log para leyenda
    breaks = log10(c(1, 10, 100, 1000, 2000))  # Puntos clave
  ) +
  labs(fill = "Minutes") +
  labs(title = "Tool Usage by Activity (min)") +
  theme_minimal()

```

### Location Analysis

``` {r , echo=FALSE}
location_summary <- data_wmbt_time_2 %>%
  group_by(`Where`) %>%
  summarise(
    n_sessions = n_distinct(`session id`),
    total_time_min = sum(total_activity) %>% round(2),
    activities_list = paste(unique(What), collapse = ", ")) %>% 
  arrange(desc(total_time_min))

kable(location_summary, caption = "Observations by Location", booktabs = TRUE) %>%
  kable_styling(full_width = FALSE)

loc_time_summary <- data_wmbt_time_2 %>%
  group_by(What) %>%
  summarise(
    n_act = n(),
    total_time = round(sum(total_activity, na.rm = TRUE),1),
    reception_desk = round(sum(total_activity[Where == "Reception Desk"], na.rm = TRUE), 1),
    Other = round(sum(total_activity[Where == "Other"], na.rm = TRUE), 1),
    waiting_area = round(sum(total_activity[Where == "Waiting Area"], na.rm = TRUE), 1),
    Hallway = round(sum(total_activity[Where == "Hallway"], na.rm = TRUE), 1),
    nurse_station = round(sum(total_activity[Where == "Nurse Station"], na.rm = TRUE), 1),
    triage_area = round(sum(total_activity[Where == "Triage Area"], na.rm = TRUE), 1),
    treatment_room = round(sum(total_activity[Where == "Treatment Room"], na.rm = TRUE), 1),
    .groups = 'drop'
  ) # %>%
  # mutate(
  #   across(ends_with("_time"), ~ round(., 2)),
  #   pct_corridors = round((Corridors / total_time) * 100, 1),
  #   pct_workstation = round((WorkStation / total_time) * 100, 1),
  #   pct_observation_room = round((Observation_Room / total_time) * 100, 1),
  #   pct_triage_Area = round((Triage_Area / total_time) * 100, 1),
  #   pct_treatment_Room = round((Treatment_Room / total_time) * 100, 1),
  #   pct_other = round((Other / total_time) * 100, 1),
  #   pct_ambulance_Bay = round((Ambulance_Bay / total_time) * 100, 1),
  #   pct_waiting_Area = round((Waiting_Area / total_time) * 100, 1),
  #   pct_xray_CT = round((XRay_CT / total_time) * 100, 1),
  #   pct_registration = round((Registration / total_time) * 100, 1),
  #   pct_plaster_Room = round((Plaster_Room / total_time) * 100, 1),
  #   pct_medication_Room = round((Medication_Room / total_time) * 100, 1), 
  #   pct_consultation_Room = round((Consultation_Room / total_time) * 100, 1)) 

loc_table <- loc_time_summary %>%
  select(What, total_time,n_act,reception_desk, Other, waiting_area,Hallway,
         nurse_station, triage_area,treatment_room) %>%
  arrange(desc(total_time))

kable(loc_table, caption = "Location by Activity (%)") %>%
  kable_styling(full_width = FALSE)

loc_hm <- loc_time_summary %>%
  select(What, Other, waiting_area,Hallway,
         nurse_station, triage_area,treatment_room) 

# Heatmap visualization
loc_hm %>%
  pivot_longer(-What, names_to = "Location", values_to = "Minutes") %>%
ggplot(aes(x = Location, y = What, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white","#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  
    breaks = log10(c(1, 10, 100, 1000, 2000))) +
  labs(fill = "Minutes") +
  labs(title = "Location by Activity (min)") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9))

```

### Tool Usage by Location

``` {r , echo=FALSE}
tool_loc_summary <- data_wmbt_time_2 %>%
  filter(!how == "None") %>% 
  group_by(Where) %>%
  summarise(
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    paper_time = round(sum(total_activity * `[How] Paper Based Record`, na.rm = TRUE), 1),
    computer_time = round(sum(total_activity * `[How] Desktop Computer`, na.rm = TRUE), 1),
    mobile_time = round(sum(total_activity * `[How] Mobile Computer`, na.rm = TRUE), 1),
    phone_time = round(sum(total_activity * `[How] Phone`, na.rm = TRUE), 1),
    total_time = round(sum(total_activity, na.rm = TRUE), 1),
    .groups = 'drop'
  ) 


kable(tool_loc_summary, caption = "Tool Usage by Location (min)") %>%
  kable_styling(full_width = FALSE)

tool_loc <- tool_loc_summary %>%
  select(
    Location = Where,
    `Paper Time` = paper_time,
    `Computer Time` = computer_time,
    `Mobile Time` = mobile_time,
    `Phone Time` = phone_time) 

# Heatmap visualization
tool_loc %>%
  pivot_longer(-Location, names_to = "Tool", values_to = "Minutes") %>%
ggplot(aes(x = Tool, y = Location, fill = log10(Minutes + 1))) +
  geom_tile(color = "grey") +
  geom_text(aes(label = round(Minutes, 1)), color = "black", size = 3) +
  scale_fill_gradientn(
    colors = c("white","#ffd700", "#fbb021", "#ee3e32"),
    labels = function(x) round(10^x, 1),  # Revertir log para leyenda
    breaks = log10(c(1, 10, 100, 1000, 2000))  # Puntos clave
  ) +
  labs(fill = "Minutes") +
  labs(title = "Tool Usage by Location (min)") +
  theme_minimal()

```
